env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
  # tsconfigRootDir: ./
  # project:
  #   - ./tsconfig.json
plugins:
  - "@typescript-eslint"
rules:
  '@typescript-eslint/interface-name-prefix': 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/no-explicit-any': 'off'

  # typescript error
  comma-dangle: "off"
  "@typescript-eslint/comma-dangle": error
  quotes: "off"
  "@typescript-eslint/quotes":
    - error
    - double
  semi: "off"
  "@typescript-eslint/semi": error